export type DegreeType = 'AA' | 'AS' | 'AAS' | 'AOT' | 'CER' | 'STC'
export type DeliveryMode = 'ground' | 'hybrid' | 'online' | 'virtual'
export type ProgramCategory = 'career-technical' | 'college-transfer' | 'health-professions' | 'business-it' | 'stem' | 'other'

export interface Program {
  id: string
  name: string
  category: ProgramCategory
  degreeType: DegreeType
  deliveryModes: DeliveryMode[]
  duration: string // e.g. "2 years", "4 semesters", "8 weeks"
  durationMonths: number
  description: string
  href: string
  tags?: string[]
  transferable: boolean
  jobPlacementRate?: number
}

export const DEGREE_TYPES: Record<DegreeType, { label: string; description: string }> = {
  AA: { label: 'Associate in Arts', description: '60 credits for 4-year transfer' },
  AS: { label: 'Associate in Science', description: '60 credits for 4-year transfer' },
  AAS: { label: 'Associate in Applied Science', description: '60-76 credits, job-ready' },
  AOT: { label: 'Associate in Occupational Technology', description: '70-76 credits, specialized' },
  CER: { label: 'Certificate', description: '42-59 credits, industry-recognized' },
  STC: { label: 'Short Certificate', description: '24-29 credits, quick credential' },
}

export const DELIVERY_MODES: Record<DeliveryMode, { label: string; icon: string }> = {
  ground: { label: 'On Campus', icon: '🏫' },
  hybrid: { label: 'Hybrid', icon: '🔀' },
  online: { label: 'Online', icon: '💻' },
  virtual: { label: 'Virtual (Live)', icon: '🎥' },
}

export const CATEGORIES: Record<ProgramCategory, { label: string; color: string }> = {
  'career-technical': { label: 'Career Technical', color: 'oklch(0.48 0.22 27)' },
  'college-transfer': { label: 'College Transfer', color: 'oklch(0.50 0.22 248)' },
  'health-professions': { label: 'Health Professions', color: 'oklch(0.68 0.20 76)' },
  'business-it': { label: 'Business & IT', color: 'oklch(0.55 0.22 28)' },
  stem: { label: 'STEM & Honors', color: 'oklch(0.62 0.22 248)' },
  other: { label: 'Other', color: 'oklch(0.22 0.17 261)' },
}

// Complete programs dataset — Business & Information Technologies + other divisions
export const SAMPLE_PROGRAMS: Program[] = [
  // ══════════════════════════════════════════════════════════════════════════════
  // BUSINESS & INFORMATION TECHNOLOGIES PROGRAMS
  // ══════════════════════════════════════════════════════════════════════════════

  // ─── Transfer Degrees (AA) ───
  {
    id: 'business-admin-aa',
    name: 'Business Administration (AA)',
    category: 'business-it',
    degreeType: 'AA',
    deliveryModes: ['ground', 'hybrid', 'online'],
    duration: '2 years',
    durationMonths: 24,
    description: 'ACBSP-accredited transfer program. Prepare for 4-year business, management, accounting, or finance degrees.',
    href: '/programs/business-administration-aa',
    tags: ['business', 'transfer', 'acbsp-accredited', 'online-available'],
    transferable: true,
  },
  {
    id: 'business-education-aa',
    name: 'Business Education (AA)',
    category: 'business-it',
    degreeType: 'AA',
    deliveryModes: ['ground', 'hybrid', 'online'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Transfer to entrepreneurship, real estate, e-commerce, or other business-related 4-year programs.',
    href: '/programs/business-education-aa',
    tags: ['business', 'transfer', 'acbsp-accredited', 'online-available'],
    transferable: true,
  },

  // ─── AAS Degrees (Job-Ready) ───
  {
    id: 'accounting-tech-aas',
    name: 'Accounting Technology (AAS)',
    category: 'business-it',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Prepare financial documents, analyze and verify accounts. QuickBooks and computerized accounting focus.',
    href: '/programs/accounting-technology-aas',
    tags: ['accounting', 'job-ready', 'computerized', 'internship'],
    transferable: false,
    jobPlacementRate: 91,
  },
  {
    id: 'business-management-aas',
    name: 'Business Administration & Management (AAS)',
    category: 'business-it',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Skills for management roles across business fields. E-commerce focus. Internship required.',
    href: '/programs/business-management-aas',
    tags: ['business', 'management', 'job-ready', 'internship'],
    transferable: false,
    jobPlacementRate: 88,
  },
  {
    id: 'computer-science-business-aas',
    name: 'Computer Science – Business (AAS)',
    category: 'business-it',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Programming and computer applications for business environments. Python, Swift, Web Development.',
    href: '/programs/computer-science-business-aas',
    tags: ['it', 'programming', 'business', 'job-ready', 'internship'],
    transferable: false,
    jobPlacementRate: 90,
  },
  {
    id: 'computer-science-general-aas',
    name: 'Computer Science – General (AAS)',
    category: 'business-it',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Networking, security, system administration, and programming. CCNA, Security+, and CompTIA paths.',
    href: '/programs/computer-science-general-aas',
    tags: ['it', 'networking', 'security', 'job-ready', 'internship', 'high-demand'],
    transferable: false,
    jobPlacementRate: 93,
  },
  {
    id: 'office-admin-general-aas',
    name: 'Office Administration – General (AAS)',
    category: 'business-it',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Administrative, computer, and interpersonal skills. Office automation and efficiency focus.',
    href: '/programs/office-admin-general-aas',
    tags: ['office', 'administration', 'job-ready', 'internship'],
    transferable: false,
    jobPlacementRate: 85,
  },
  {
    id: 'office-admin-legal-aas',
    name: 'Office Administration – Legal (AAS)',
    category: 'business-it',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Paralegal-focused program. Legal concepts, business law, transcription, and office procedures.',
    href: '/programs/office-admin-legal-aas',
    tags: ['legal', 'paralegal', 'office', 'job-ready', 'internship'],
    transferable: false,
    jobPlacementRate: 87,
  },
  {
    id: 'medical-office-admin-aas',
    name: 'Medical Office Administration (AAS)',
    category: 'business-it',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Medical coding, billing, terminology, and office procedures. Multiple industry certifications available.',
    href: '/programs/medical-office-admin-aas',
    tags: ['healthcare', 'medical-coding', 'office', 'job-ready', 'internship', 'certifications'],
    transferable: false,
    jobPlacementRate: 92,
  },

  // ─── Certificates ───
  {
    id: 'accounting-tech-cer',
    name: 'Accounting Technology (Certificate)',
    category: 'business-it',
    degreeType: 'CER',
    deliveryModes: ['ground', 'hybrid'],
    duration: '1 year',
    durationMonths: 12,
    description: 'Career change program. Accounting skills and QuickBooks proficiency without full degree requirements.',
    href: '/programs/accounting-tech-certificate',
    tags: ['accounting', 'certificate', 'career-change'],
    transferable: false,
  },
  {
    id: 'computer-science-cer',
    name: 'Computer Science (Certificate)',
    category: 'business-it',
    degreeType: 'CER',
    deliveryModes: ['ground', 'hybrid'],
    duration: '1 year',
    durationMonths: 12,
    description: 'Networking, security, and infrastructure fundamentals. CompTIA A+ and Network+ paths available.',
    href: '/programs/computer-science-certificate',
    tags: ['it', 'networking', 'security', 'certificate'],
    transferable: false,
    jobPlacementRate: 91,
  },
  {
    id: 'cybersecurity-cer',
    name: 'Computer Science – Cybersecurity (Certificate)',
    category: 'business-it',
    degreeType: 'CER',
    deliveryModes: ['ground', 'online'],
    duration: '1 year',
    durationMonths: 12,
    description: 'Protect critical systems and data. CompTIA Security+, CySA+, and Ethical Hacking certifications.',
    href: '/programs/cybersecurity-certificate',
    tags: ['it', 'security', 'cybersecurity', 'certificate', 'high-demand'],
    transferable: false,
    jobPlacementRate: 94,
  },

  // ─── Short Certificates (STC) ───
  {
    id: 'cybersecurity-stc',
    name: 'Cybersecurity (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'online'],
    duration: '6 months',
    durationMonths: 6,
    description: 'Fast-track cybersecurity credential. CompTIA Security+ and ethical hacking fundamentals.',
    href: '/programs/cybersecurity-short-certificate',
    tags: ['it', 'security', 'short-certificate', 'high-demand'],
    transferable: false,
    jobPlacementRate: 93,
  },
  {
    id: 'cloud-computing-stc',
    name: 'Cloud Computing (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'online'],
    duration: '6 months',
    durationMonths: 6,
    description: 'AWS Cloud Practitioner certification. Infrastructure, services, and cloud migration fundamentals.',
    href: '/programs/cloud-computing-short-certificate',
    tags: ['it', 'cloud', 'aws', 'short-certificate', 'high-demand'],
    transferable: false,
    jobPlacementRate: 92,
  },
  {
    id: 'web-development-stc',
    name: 'Web Technologies (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'online'],
    duration: '6 months',
    durationMonths: 6,
    description: 'Front-end and back-end web development. HTML, CSS, JavaScript, and PHP fundamentals.',
    href: '/programs/web-technologies-short-certificate',
    tags: ['it', 'web-development', 'short-certificate'],
    transferable: false,
    jobPlacementRate: 89,
  },
  {
    id: 'app-dev-swift-stc',
    name: 'App Development – Swift (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'online'],
    duration: '5 months',
    durationMonths: 5,
    description: 'iOS app development with Swift. CertiPort certification included.',
    href: '/programs/app-dev-swift-short-certificate',
    tags: ['it', 'app-development', 'ios', 'short-certificate'],
    transferable: false,
    jobPlacementRate: 88,
  },
  {
    id: 'networking-stc',
    name: 'Networking (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'hybrid'],
    duration: '6 months',
    durationMonths: 6,
    description: 'CCNA and CompTIA Network+ preparation. LAN, WAN, and network administration.',
    href: '/programs/networking-short-certificate',
    tags: ['it', 'networking', 'ccna', 'short-certificate', 'high-demand'],
    transferable: false,
    jobPlacementRate: 91,
  },
  {
    id: 'desktop-support-stc',
    name: 'Desktop Support Technician (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'hybrid'],
    duration: '6 months',
    durationMonths: 6,
    description: 'A+ and CompTIA certification path. Hardware, software support, and troubleshooting.',
    href: '/programs/desktop-support-technician-short-certificate',
    tags: ['it', 'support', 'a-plus', 'short-certificate'],
    transferable: false,
    jobPlacementRate: 87,
  },
  {
    id: 'management-supervision-stc',
    name: 'Management and Supervision (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'hybrid'],
    duration: '5 months',
    durationMonths: 5,
    description: 'Leadership skills for supervisors and managers. Goal setting, team building, communication.',
    href: '/programs/management-supervision-short-certificate',
    tags: ['management', 'leadership', 'short-certificate'],
    transferable: false,
    jobPlacementRate: 86,
  },
  {
    id: 'real-estate-stc',
    name: 'Real Estate (Short Certificate)',
    category: 'business-it',
    degreeType: 'STC',
    deliveryModes: ['ground', 'hybrid'],
    duration: '4 months',
    durationMonths: 4,
    description: 'Pre-licensure program. 60 hours meeting Alabama Real Estate Commission standards.',
    href: '/programs/real-estate-short-certificate',
    tags: ['real-estate', 'pre-license', 'short-certificate'],
    transferable: false,
    jobPlacementRate: 88,
  },

  // ════════════════════════════════════════════════════════════════════════════════
  // OTHER DIVISIONS (sample programs)
  // ════════════════════════════════════════════════════════════════════════════════

  {
    id: 'nursing-rn',
    name: 'Nursing (RN)',
    category: 'health-professions',
    degreeType: 'AAS',
    deliveryModes: ['ground', 'hybrid'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Top 10 RN Program in Alabama. NCLEX-RN preparation with clinical rotations at partner hospitals.',
    href: '/programs/nursing-rn',
    tags: ['healthcare', 'licensed-profession', 'high-demand'],
    transferable: true,
    jobPlacementRate: 96,
  },
  {
    id: 'general-studies-aa',
    name: 'General Studies (AA)',
    category: 'college-transfer',
    degreeType: 'AA',
    deliveryModes: ['ground', 'hybrid', 'online'],
    duration: '2 years',
    durationMonths: 24,
    description: 'Transfer to 4-year university. Partner agreements with 20+ schools including Auburn, Alabama, UAB.',
    href: '/programs/general-studies-aa',
    tags: ['transfer', 'liberal-arts', 'online-available'],
    transferable: true,
  },
]
